/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ActivityRouteImport } from './routes/activity'
import { Route as CreateRouteImport } from './routes/create'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as ListingsRouteImport } from './routes/listings'
import { Route as MyActivityRouteImport } from './routes/my-activity'
import { Route as MyNftsRouteImport } from './routes/my-nfts'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as CollectionsSlugRouteImport } from './routes/collections.$slug'
import { Route as CollectionsTheRoninRouteImport } from './routes/collections.the-ronin'
import { Route as NftsIdRouteImport } from './routes/nfts.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityRoute = ActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const ListingsRoute = ListingsRouteImport.update({
  id: '/listings',
  path: '/listings',
  getParentRoute: () => rootRouteImport,
} as any)
const MyActivityRoute = MyActivityRouteImport.update({
  id: '/my-activity',
  path: '/my-activity',
  getParentRoute: () => rootRouteImport,
} as any)
const MyNftsRoute = MyNftsRouteImport.update({
  id: '/my-nfts',
  path: '/my-nfts',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsSlugRoute = CollectionsSlugRouteImport.update({
  id: '/collections/$slug',
  path: '/collections/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsTheRoninRoute = CollectionsTheRoninRouteImport.update({
  id: '/collections/the-ronin',
  path: '/collections/the-ronin',
  getParentRoute: () => rootRouteImport,
} as any)
const NftsIdRoute = NftsIdRouteImport.update({
  id: '/nfts/$id',
  path: '/nfts/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/create': typeof CreateRoute
  '/explore': typeof ExploreRoute
  '/listings': typeof ListingsRoute
  '/my-activity': typeof MyActivityRoute
  '/my-nfts': typeof MyNftsRoute
  '/profile': typeof ProfileRoute
  '/collections/$slug': typeof CollectionsSlugRoute
  '/collections/the-ronin': typeof CollectionsTheRoninRoute
  '/nfts/$id': typeof NftsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/create': typeof CreateRoute
  '/explore': typeof ExploreRoute
  '/listings': typeof ListingsRoute
  '/my-activity': typeof MyActivityRoute
  '/my-nfts': typeof MyNftsRoute
  '/profile': typeof ProfileRoute
  '/collections/$slug': typeof CollectionsSlugRoute
  '/collections/the-ronin': typeof CollectionsTheRoninRoute
  '/nfts/$id': typeof NftsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/create': typeof CreateRoute
  '/explore': typeof ExploreRoute
  '/listings': typeof ListingsRoute
  '/my-activity': typeof MyActivityRoute
  '/my-nfts': typeof MyNftsRoute
  '/profile': typeof ProfileRoute
  '/collections/$slug': typeof CollectionsSlugRoute
  '/collections/the-ronin': typeof CollectionsTheRoninRoute
  '/nfts/$id': typeof NftsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activity'
    | '/create'
    | '/explore'
    | '/listings'
    | '/my-activity'
    | '/my-nfts'
    | '/profile'
    | '/collections/$slug'
    | '/collections/the-ronin'
    | '/nfts/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activity'
    | '/create'
    | '/explore'
    | '/listings'
    | '/my-activity'
    | '/my-nfts'
    | '/profile'
    | '/collections/$slug'
    | '/collections/the-ronin'
    | '/nfts/$id'
  id:
    | '__root__'
    | '/'
    | '/activity'
    | '/create'
    | '/explore'
    | '/listings'
    | '/my-activity'
    | '/my-nfts'
    | '/profile'
    | '/collections/$slug'
    | '/collections/the-ronin'
    | '/nfts/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivityRoute: typeof ActivityRoute
  CreateRoute: typeof CreateRoute
  ExploreRoute: typeof ExploreRoute
  ListingsRoute: typeof ListingsRoute
  MyActivityRoute: typeof MyActivityRoute
  MyNftsRoute: typeof MyNftsRoute
  ProfileRoute: typeof ProfileRoute
  CollectionsSlugRoute: typeof CollectionsSlugRoute
  CollectionsTheRoninRoute: typeof CollectionsTheRoninRoute
  NftsIdRoute: typeof NftsIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity': {
      id: '/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listings': {
      id: '/listings'
      path: '/listings'
      fullPath: '/listings'
      preLoaderRoute: typeof ListingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-activity': {
      id: '/my-activity'
      path: '/my-activity'
      fullPath: '/my-activity'
      preLoaderRoute: typeof MyActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-nfts': {
      id: '/my-nfts'
      path: '/my-nfts'
      fullPath: '/my-nfts'
      preLoaderRoute: typeof MyNftsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/$slug': {
      id: '/collections/$slug'
      path: '/collections/$slug'
      fullPath: '/collections/$slug'
      preLoaderRoute: typeof CollectionsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/the-ronin': {
      id: '/collections/the-ronin'
      path: '/collections/the-ronin'
      fullPath: '/collections/the-ronin'
      preLoaderRoute: typeof CollectionsTheRoninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nfts/$id': {
      id: '/nfts/$id'
      path: '/nfts/$id'
      fullPath: '/nfts/$id'
      preLoaderRoute: typeof NftsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivityRoute: ActivityRoute,
  CreateRoute: CreateRoute,
  ExploreRoute: ExploreRoute,
  ListingsRoute: ListingsRoute,
  MyActivityRoute: MyActivityRoute,
  MyNftsRoute: MyNftsRoute,
  ProfileRoute: ProfileRoute,
  CollectionsSlugRoute: CollectionsSlugRoute,
  CollectionsTheRoninRoute: CollectionsTheRoninRoute,
  NftsIdRoute: NftsIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
